### ISSUE TITLE
Get a much lower performance, which can't achieve the given Baseline Performance (F-measure: 35.10%)

### ISSUE THREAD

**Issue by dby124** [c4dm/dcase-few-shot-bioacoustic#13]
When run the ./DCASE2021/task5-dcase-few-shot-bioacoustic/baselines/deep_learning/main.py, I get a lower baseline performance than 35.10%. 
Moreover, I get different performance although I load the same best model.

The running command:
CUDA_VISIBLE_DEVICES=3 python main.py
python post_proc.py -val_path=/Development_Set/Validation_Set/ -evaluation_file=Eval_out.csv -new_evaluation_file=Eval_out_new.csv
python evaluation.py -pred_file=Eval_out_new.csv -ref_files_path=/Development_Set/Validation_Set/ -team_name=TESTteam -dataset=VAL -savepath=./

The baseline performance I got is about 27% (F-measure), which is much less than  the given Baseline Performance (F-measure: 35.10%). Is it normal?

I tested the performance based on the given Baseline best model (/baselines/deep_learning/model weights/best_model.pth). I run tested it for 3 times. The results are shown as following.

Evaluation for: TESTteam VAL
BUK1_20181011_001004.wav {'TP': 5, 'FP': 2, 'FN': 26, 'total_n_pos_events': 31}
BUK1_20181013_023504.wav {'TP': 0, 'FP': 13, 'FN': 24, 'total_n_pos_events': 24}
BUK4_20161011_000804.wav {'TP': 0, 'FP': 18, 'FN': 47, 'total_n_pos_events': 47}
BUK4_20171022_004304a.wav {'TP': 5, 'FP': 12, 'FN': 12, 'total_n_pos_events': 17}
BUK5_20161101_002104a.wav {'TP': 22, 'FP': 6, 'FN': 66, 'total_n_pos_events': 88}
BUK5_20180921_015906a.wav {'TP': 2, 'FP': 10, 'FN': 21, 'total_n_pos_events': 23}
a1.wav {'TP': 19, 'FP': 14, 'FN': 3, 'total_n_pos_events': 22}
Overall_scores: {'precision': 0.4414075845575675, 'recall': 0.21898305084745762, 'fmeasure (percentage)': 29.274}

Evaluation for: TESTteam VAL
BUK1_20181011_001004.wav {'TP': 2, 'FP': 5, 'FN': 29, 'total_n_pos_events': 31}
BUK1_20181013_023504.wav {'TP': 2, 'FP': 13, 'FN': 22, 'total_n_pos_events': 24}
BUK4_20161011_000804.wav {'TP': 0, 'FP': 19, 'FN': 47, 'total_n_pos_events': 47}
BUK4_20171022_004304a.wav {'TP': 7, 'FP': 13, 'FN': 10, 'total_n_pos_events': 17}
BUK5_20161101_002104a.wav {'TP': 21, 'FP': 5, 'FN': 67, 'total_n_pos_events': 88}
BUK5_20180921_015906a.wav {'TP': 1, 'FP': 14, 'FN': 22, 'total_n_pos_events': 23}
a1.wav {'TP': 19, 'FP': 13, 'FN': 3, 'total_n_pos_events': 22}
Overall_scores: {'precision': 0.41883767535070143, 'recall': 0.21417591801878738, 'fmeasure (percentage)': 28.342}

Evaluation for: TESTteam VAL
BUK1_20181011_001004.wav {'TP': 2, 'FP': 3, 'FN': 29, 'total_n_pos_events': 31}
BUK1_20181013_023504.wav {'TP': 2, 'FP': 12, 'FN': 22, 'total_n_pos_events': 24}
BUK4_20161011_000804.wav {'TP': 0, 'FP': 19, 'FN': 47, 'total_n_pos_events': 47}
BUK4_20171022_004304a.wav {'TP': 5, 'FP': 10, 'FN': 12, 'total_n_pos_events': 17}
BUK5_20161101_002104a.wav {'TP': 15, 'FP': 7, 'FN': 73, 'total_n_pos_events': 88}
BUK5_20180921_015906a.wav {'TP': 1, 'FP': 10, 'FN': 22, 'total_n_pos_events': 23}
a1.wav {'TP': 19, 'FP': 12, 'FN': 3, 'total_n_pos_events': 22}
Overall_scores: {'precision': 0.39435450394354504, 'recall': 0.17288444040036396, 'fmeasure (percentage)': 24.038}

**Comment by veronicamorfi** [comment]
There is some randomness in the model, due to the negative prototype selection for the validation set. Also, different GPUs can have different results due to possible architecture differences. The results reported are from a RTX 2080 Ti. 

We are also checking to make sure the initialisation seeds are all pre-set and there is no more randomness added from that. I'll update this issue with more information soon.

**Comment by shubhr** [comment]
I have updated main.py and now the network is giving a more consistent result across gpus. The variation is around 3 %. Two changes in the code :
1) num_workers = 0
2) init_seed() function, where torch.manual_seed() and torch.cuda.manual_seed() is set. 

If you are still getting high variations in your results, please let me know.
