### ISSUE TITLE
Can't replicate the the baseline results. F1 score near zero 

### ISSUE THREAD

**Issue by MichalBortkiewicz** [c4dm/dcase-few-shot-bioacoustic#14]
Hi!

I am following the README files instruction (baselines\deep_learning\README.md and evaluation_metrics\README.md) for running the experiment using the pretrained protonet based on ResNet. The commands I ran to replicate:

1. `python main.py -set.features=true`
2. `python main.py -set.eval=true` (using the best_model.pth)
3. `python post_proc.py -val_path=/Development_Set/Validation_Set/ -evaluation_file=Eval_out.csv -new_evaluation_file=Eval_out_new.csv`
4. `python evaluation.py -pred_file=Eval_out_new.csv -ref_files_path=/Development_Set/Validation_Set/ -team_name=TESTteam -dataset=VAL -savepath=./`

However, the resulting metrics are super poor (attached below). 

Am I omitting some steps of evaluation?

`Evaluation for: TESTteam VAL
#423-487.wav {'TP': 0, 'FP': 4, 'FN': 4, 'total_n_pos_events': 4}
#97-113.wav {'TP': 1, 'FP': 38, 'FN': 9, 'total_n_pos_events': 10}
BUK1_20181011_001004.wav {'TP': 1, 'FP': 26, 'FN': 30, 'total_n_pos_events': 31}
BUK1_20181013_023504.wav {'TP': 0, 'FP': 407, 'FN': 24, 'total_n_pos_events': 24}
BUK4_20161011_000804.wav {'TP': 0, 'FP': 77, 'FN': 47, 'total_n_pos_events': 47}
BUK4_20171022_004304a.wav {'TP': 0, 'FP': 2, 'FN': 17, 'total_n_pos_events': 17}
BUK5_20161101_002104a.wav {'TP': 0, 'FP': 13, 'FN': 88, 'total_n_pos_events': 88}
DCASE2021-ML_168236.wav {'TP': 8, 'FP': 18, 'FN': 102, 'total_n_pos_events': 110}
DCASE2021-ML_273164.wav {'TP': 0, 'FP': 1, 'FN': 150, 'total_n_pos_events': 150}
DCASE2021-ML_72010931.wav {'TP': 0, 'FP': 1, 'FN': 59, 'total_n_pos_events': 59}
DCASE2021-ML_89792.wav {'TP': 0, 'FP': 6, 'FN': 29, 'total_n_pos_events': 29}
ME1.wav {'TP': 0, 'FP': 3, 'FN': 11, 'total_n_pos_events': 11}
R4_cleaned recording_13-10-17.wav {'TP': 0, 'FP': 23, 'FN': 19, 'total_n_pos_events': 19}
R4_cleaned recording_16-10-17.wav {'TP': 0, 'FP': 26, 'FN': 34, 'total_n_pos_events': 34}
R4_cleaned recording_17-10-17.wav {'TP': 0, 'FP': 31, 'FN': 36, 'total_n_pos_events': 36}
R4_cleaned recording_TEL_19-10-17.wav {'TP': 0, 'FP': 47, 'FN': 54, 'total_n_pos_events': 54}
R4_cleaned recording_TEL_20-10-17.wav {'TP': 1, 'FP': 40, 'FN': 64, 'total_n_pos_events': 65}
R4_cleaned recording_TEL_23-10-17.wav {'TP': 0, 'FP': 70, 'FN': 84, 'total_n_pos_events': 84}
R4_cleaned recording_TEL_24-10-17.wav {'TP': 1, 'FP': 56, 'FN': 98, 'total_n_pos_events': 99}
R4_cleaned recording_TEL_25-10-17.wav {'TP': 1, 'FP': 77, 'FN': 99, 'total_n_pos_events': 100}

Overall_scores: {'precision': 3.97478989509039e-05, 'recall': 3.980569843451652e-05, 'fmeasure (percentage)': 0.004}
`

**Comment by shubhr** [comment]
Hey Michal. I have updated the code in main.py, util.py and Datagenerator.py.  The post processing file to be executed is post_proc_new.py. It contains a hard coded version of post processing as compared to post_proc.py, which is adaptive. The reported results were obtained using post_proc_new.py. 

Let me know if you cant still replicate the results. 

This is what you should get :

Evaluation for: TESTteam VAL
#423-487.wav {'TP': 4, 'FP': 0, 'FN': 0, 'total_n_pos_events': 4}
#97-113.wav {'TP': 2, 'FP': 113, 'FN': 8, 'total_n_pos_events': 10}
BUK1_20181011_001004.wav {'TP': 11, 'FP': 67, 'FN': 20, 'total_n_pos_events': 31}
BUK1_20181013_023504.wav {'TP': 0, 'FP': 5, 'FN': 24, 'total_n_pos_events': 24}
BUK4_20161011_000804.wav {'TP': 0, 'FP': 8, 'FN': 47, 'total_n_pos_events': 47}
BUK4_20171022_004304a.wav {'TP': 4, 'FP': 13, 'FN': 13, 'total_n_pos_events': 17}
BUK5_20161101_002104a.wav {'TP': 24, 'FP': 120, 'FN': 64, 'total_n_pos_events': 88}
BUK5_20180921_015906a.wav {'TP': 0, 'FP': 2, 'FN': 23, 'total_n_pos_events': 23}
DCASE2021-ML_129696.wav {'TP': 1, 'FP': 1, 'FN': 75, 'total_n_pos_events': 76}
DCASE2021-ML_131198.wav {'TP': 2, 'FP': 2, 'FN': 2, 'total_n_pos_events': 4}
DCASE2021-ML_131369.wav {'TP': 1, 'FP': 0, 'FN': 39, 'total_n_pos_events': 40}
DCASE2021-ML_168236.wav {'TP': 42, 'FP': 16, 'FN': 68, 'total_n_pos_events': 110}
DCASE2021-ML_176488.wav {'TP': 1, 'FP': 1, 'FN': 8, 'total_n_pos_events': 9}
DCASE2021-ML_190099.wav {'TP': 9, 'FP': 3, 'FN': 6, 'total_n_pos_events': 15}
DCASE2021-ML_191491.wav {'TP': 4, 'FP': 1, 'FN': 5, 'total_n_pos_events': 9}
DCASE2021-ML_197045.wav {'TP': 15, 'FP': 0, 'FN': 59, 'total_n_pos_events': 74}
DCASE2021-ML_268995.wav {'TP': 1, 'FP': 0, 'FN': 9, 'total_n_pos_events': 10}
DCASE2021-ML_37045.wav {'TP': 8, 'FP': 0, 'FN': 4, 'total_n_pos_events': 12}
DCASE2021-ML_521435.wav {'TP': 37, 'FP': 2, 'FN': 21, 'total_n_pos_events': 58}
DCASE2021-ML_72010931.wav {'TP': 7, 'FP': 1, 'FN': 52, 'total_n_pos_events': 59}
DCASE2021-ML_89792.wav {'TP': 27, 'FP': 0, 'FN': 2, 'total_n_pos_events': 29}
ME1.wav {'TP': 7, 'FP': 10, 'FN': 4, 'total_n_pos_events': 11}
ME2.wav {'TP': 14, 'FP': 0, 'FN': 27, 'total_n_pos_events': 41}
R4_cleaned recording_13-10-17.wav {'TP': 19, 'FP': 5, 'FN': 0, 'total_n_pos_events': 19}
R4_cleaned recording_16-10-17.wav {'TP': 16, 'FP': 31, 'FN': 18, 'total_n_pos_events': 34}
R4_cleaned recording_17-10-17.wav {'TP': 27, 'FP': 39, 'FN': 9, 'total_n_pos_events': 36}
R4_cleaned recording_TEL_19-10-17.wav {'TP': 49, 'FP': 4, 'FN': 5, 'total_n_pos_events': 54}
R4_cleaned recording_TEL_20-10-17.wav {'TP': 49, 'FP': 23, 'FN': 16, 'total_n_pos_events': 65}
R4_cleaned recording_TEL_23-10-17.wav {'TP': 82, 'FP': 4, 'FN': 2, 'total_n_pos_events': 84}
R4_cleaned recording_TEL_24-10-17.wav {'TP': 70, 'FP': 17, 'FN': 29, 'total_n_pos_events': 99}
R4_cleaned recording_TEL_25-10-17.wav {'TP': 45, 'FP': 70, 'FN': 55, 'total_n_pos_events': 100}

Overall_scores: {'precision': 0.3634321892823061, 'recall': 0.249643081187092, 'fmeasure (percentage)': 29.598}

**Comment by MichalBortkiewicz** [comment]
@shubhr thank you for the update. Indeed, now I get better results (still slightly worse than yours due to the negative prototypes choice I guess):

Evaluation for: TESTteam VAL
#423-487.wav {'TP': 3, 'FP': 4, 'FN': 1, 'total_n_pos_events': 4}
#97-113.wav {'TP': 8, 'FP': 133, 'FN': 2, 'total_n_pos_events': 10}
BUK1_20181011_001004.wav {'TP': 9, 'FP': 74, 'FN': 22, 'total_n_pos_events': 31}
BUK1_20181013_023504.wav {'TP': 0, 'FP': 215, 'FN': 24, 'total_n_pos_events': 24}
BUK4_20161011_000804.wav {'TP': 0, 'FP': 14, 'FN': 47, 'total_n_pos_events': 47}
BUK4_20171022_004304a.wav {'TP': 4, 'FP': 13, 'FN': 13, 'total_n_pos_events': 17}
BUK5_20161101_002104a.wav {'TP': 25, 'FP': 15, 'FN': 63, 'total_n_pos_events': 88}
BUK5_20180921_015906a.wav {'TP': 1, 'FP': 4, 'FN': 22, 'total_n_pos_events': 23}
DCASE2021-ML_131198.wav {'TP': 2, 'FP': 2, 'FN': 2, 'total_n_pos_events': 4}
DCASE2021-ML_131369.wav {'TP': 3, 'FP': 0, 'FN': 37, 'total_n_pos_events': 40}
DCASE2021-ML_168236.wav {'TP': 37, 'FP': 0, 'FN': 73, 'total_n_pos_events': 110}
DCASE2021-ML_176488.wav {'TP': 2, 'FP': 1, 'FN': 7, 'total_n_pos_events': 9}
DCASE2021-ML_190099.wav {'TP': 11, 'FP': 3, 'FN': 4, 'total_n_pos_events': 15}
DCASE2021-ML_191491.wav {'TP': 5, 'FP': 1, 'FN': 4, 'total_n_pos_events': 9}
DCASE2021-ML_197045.wav {'TP': 31, 'FP': 0, 'FN': 43, 'total_n_pos_events': 74}
DCASE2021-ML_268995.wav {'TP': 5, 'FP': 0, 'FN': 5, 'total_n_pos_events': 10}
DCASE2021-ML_37045.wav {'TP': 7, 'FP': 0, 'FN': 5, 'total_n_pos_events': 12}
DCASE2021-ML_521435.wav {'TP': 40, 'FP': 8, 'FN': 18, 'total_n_pos_events': 58}
DCASE2021-ML_72010931.wav {'TP': 36, 'FP': 5, 'FN': 23, 'total_n_pos_events': 59}
DCASE2021-ML_89792.wav {'TP': 26, 'FP': 0, 'FN': 3, 'total_n_pos_events': 29}
ME1.wav {'TP': 8, 'FP': 9, 'FN': 3, 'total_n_pos_events': 11}
ME2.wav {'TP': 7, 'FP': 1, 'FN': 34, 'total_n_pos_events': 41}
R4_cleaned recording_13-10-17.wav {'TP': 18, 'FP': 13, 'FN': 1, 'total_n_pos_events': 19}
R4_cleaned recording_16-10-17.wav {'TP': 20, 'FP': 28, 'FN': 14, 'total_n_pos_events': 34}
R4_cleaned recording_17-10-17.wav {'TP': 3, 'FP': 52, 'FN': 33, 'total_n_pos_events': 36}
R4_cleaned recording_TEL_19-10-17.wav {'TP': 47, 'FP': 18, 'FN': 7, 'total_n_pos_events': 54}
R4_cleaned recording_TEL_20-10-17.wav {'TP': 35, 'FP': 34, 'FN': 30, 'total_n_pos_events': 65}
R4_cleaned recording_TEL_23-10-17.wav {'TP': 72, 'FP': 22, 'FN': 12, 'total_n_pos_events': 84}
R4_cleaned recording_TEL_24-10-17.wav {'TP': 70, 'FP': 29, 'FN': 29, 'total_n_pos_events': 99}
R4_cleaned recording_TEL_25-10-17.wav {'TP': 44, 'FP': 85, 'FN': 56, 'total_n_pos_events': 100}

Overall_scores: {'precision': 0.2728471785448524, 'recall': 0.25480425256385947, 'fmeasure (percentage)': 26.352}

Do you think such deviation from your results is plausible?

**Comment by shubhr** [comment]
@MichalBortkiewicz  I think its plausible depending upon the number of samples you select for the negative prototype. My choice of the number was purely guided by fitment on a single GPU. I guess varying the number of samples for negative prototype would definitely deviate the score.  

Are you getting a different score with the same number of samples?

**Comment by shubhr** [comment]
Thank you Michal.
